version: '3.8'

services:

  postgres:
    image: postgres:14
    container_name: autoscaling_postgres
    environment:
      POSTGRES_DB: autoscaling_db
      POSTGRES_USER: autoscaling_user
      POSTGRES_PASSWORD: autoscaling_pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autoscaling_user -d autoscaling_db"]
      interval: 5s
      timeout: 5s
      retries: 5