
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: autoscaling_postgres
    environment:
      POSTGRES_DB: autoscaling_db
      POSTGRES_USER: autoscaling_user
      POSTGRES_PASSWORD: autoscaling_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autoscaling_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autoscaling_user -d autoscaling_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: autoscaling_backend
    environment:
      DATABASE_URL: postgresql://autoscaling_user:autoscaling_pass@postgres:5432/autoscaling_db
      SECRET_KEY: your-secret-key-change-in-production
      CORS_ORIGINS: http://localhost:5173,http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - autoscaling_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: autoscaling_frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:8000
    networks:
      - autoscaling_network
    command: npm run dev -- --host 0.0.0.0 --port 3000
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  autoscaling_network:
    driver: bridge
