
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: autoscaling_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: autoscaling_db
      MYSQL_USER: autoscaling_user
      MYSQL_PASSWORD: autoscaling_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - autoscaling_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: autoscaling_backend
    environment:
      DATABASE_URL: mysql+pymysql://autoscaling_user:autoscaling_pass@mysql:3306/autoscaling_db
      SECRET_KEY: your-secret-key-change-in-production
      CORS_ORIGINS: http://localhost:5173,http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - autoscaling_network
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: autoscaling_frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:8000
    networks:
      - autoscaling_network
#    volumes:
#      - .:/app
#      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  autoscaling_network:
    driver: bridge
