
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: autoscaling_postgres
    environment:
      POSTGRES_DB: autoscaling_db
      POSTGRES_USER: autoscaling_user
      POSTGRES_PASSWORD: autoscaling_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autoscaling_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autoscaling_user -d autoscaling_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: autoscaling_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - autoscaling_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug --access-log

  frontend:
    image: node:18-alpine
    container_name: autoscaling_frontend
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
      - VITE_KEYCLOAK_URL=${VITE_KEYCLOAK_URL:-}
      - VITE_KEYCLOAK_REALM=${VITE_KEYCLOAK_REALM:-}
      - VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID:-}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - autoscaling_network
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 3000"
    depends_on:
      - backend

networks:
  autoscaling_network:
    driver: bridge
  